# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WeatherApp

    pod 'SDWebImage', '~> 3.8'
    pod 'AFNetworking', '~> 3.1'
end
