# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Expanding-Collection' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Expanding-Collection

  target 'Expanding-CollectionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Expanding-CollectionUITests' do
    inherit! :search_paths
    # Pods for testing

    pod 'expanding-collection', '~> 1.0'

  end

end
