# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Project1101' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Project1101

  target 'Project1101Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Project1101UITests' do
    inherit! :search_paths
    # Pods for testing
  pod 'SidebarOverlay', '~> 3.1'  

  end

end
